server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/testspringboot"
    username: root
    password: "921127"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
